source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'CZBLEControl' do
    
    pod 'GoogleAPIClientForREST/Drive', '~> 1.4'
    pod 'GTMAppAuth'
    pod 'AppAuth', '~> 1.0'
    
    pod 'Firebase'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Performance'
    
    pod 'SwiftyDropbox'
    
    pod 'MBProgressHUD', '~> 1.2.0'
    
end

